version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: zod
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
      - dependency-name: "@typescript-eslint/*"
        update-types:
          - version-update:semver-major
      - dependency-name: vite
        update-types:
          - version-update:semver-major
      - dependency-name: vitest
        update-types:
          - version-update:semver-major
  - package-ecosystem: pip
    directory: /packages/uns-py
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
