from __future__ import annotations

import sys

from .api import (
    ApiEventContext,
    ApiProxyOptions,
    GetEndpointOptions,
    PostEndpointOptions,
    QueryParamDef,
    UnsApiProxy,
)
from .core import (
    AuthClient,
    BatchRangeResponse,
    BatchRangeTopicResult,
    ClientError,
    ConfigFile,
    DataPayload,
    FileStore,
    HostResolverOptions,
    InfisicalResolverOptions,
    LastValueResult,
    MessageMode,
    RangeQuery,
    RangeResult,
    RUNTIME_METADATA,
    RawResponse,
    SecretResolverOptions,
    SecureStore,
    SecureStoreFactory,
    StatusMonitor,
    TablePayload,
    TopicBuilder,
    UnsClient,
    UnsMqttClient,
    UnsMqttProxy,
    UnsPacket,
    UnsParameters,
    UnsProcessParameters,
    UnsProxyProcess,
    base_config_schema,
    boolean_schema,
    build_uns_identity_path,
    build_uns_route_path,
    compose_config_schema,
    generate_config_schema,
    host_value_schema,
    integer_schema,
    load_project_extras_schema,
    resolve_infisical_config,
    secret_value_schema,
    strict_object,
    string_schema,
)
from .cron import CronProxyOptions, CronSchedule, CronScheduleInput, UnsCronProxy
from .database import (
    DatabaseClient,
    DatabaseConnectionConfig,
    DatabaseDialect,
    DatabaseExecuteResult,
    DatabaseManager,
    DatabaseQueryResult,
    OracleDatabaseConfig,
    PostgresDatabaseConfig,
    SqlParams,
    SqliteDatabaseConfig,
    compile_named_params,
    create_database_client,
    database_project_extras_schema,
    get_database,
    get_database_manager,
    load_sql_file,
    register_database,
    resolve_sql_file_path,
)
from .version import __version__

if sys.platform.startswith("win"):
    try:
        import asyncio

        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    except Exception:  # pragma: no cover
        pass

__all__ = [
    "ConfigFile",
    "base_config_schema",
    "compose_config_schema",
    "generate_config_schema",
    "load_project_extras_schema",
    "strict_object",
    "string_schema",
    "integer_schema",
    "boolean_schema",
    "host_value_schema",
    "secret_value_schema",
    "RUNTIME_METADATA",
    "SecretResolverOptions",
    "InfisicalResolverOptions",
    "HostResolverOptions",
    "resolve_infisical_config",
    "UnsPacket",
    "DataPayload",
    "TablePayload",
    "TopicBuilder",
    "UnsMqttClient",
    "StatusMonitor",
    "UnsMqttProxy",
    "MessageMode",
    "UnsProxyProcess",
    "UnsProcessParameters",
    "UnsParameters",
    "UnsApiProxy",
    "ApiProxyOptions",
    "GetEndpointOptions",
    "PostEndpointOptions",
    "QueryParamDef",
    "ApiEventContext",
    "UnsCronProxy",
    "CronProxyOptions",
    "CronSchedule",
    "CronScheduleInput",
    "UnsClient",
    "AuthClient",
    "RawResponse",
    "RangeQuery",
    "RangeResult",
    "BatchRangeTopicResult",
    "BatchRangeResponse",
    "LastValueResult",
    "ClientError",
    "SecureStore",
    "SecureStoreFactory",
    "FileStore",
    "build_uns_identity_path",
    "build_uns_route_path",
    "DatabaseDialect",
    "SqlParams",
    "DatabaseClient",
    "DatabaseQueryResult",
    "DatabaseExecuteResult",
    "DatabaseConnectionConfig",
    "PostgresDatabaseConfig",
    "SqliteDatabaseConfig",
    "OracleDatabaseConfig",
    "DatabaseManager",
    "database_project_extras_schema",
    "compile_named_params",
    "load_sql_file",
    "resolve_sql_file_path",
    "create_database_client",
    "register_database",
    "get_database_manager",
    "get_database",
    "__version__",
]
