// Shared list of common UNS attributes to improve IntelliSense while allowing custom values.
export const knownUnsAttributes = [
  // Equipment measurements and status
  "measured-temperature",
  "measured-vibration",
  "measured-pressure",
  "measured-flow",
  "status",
  "operating-hours",
  "fault-code",
  "speed",
  "energy-consumption",
  "power",
  "voltage",
  "current",
  // Material and lot info
  "lot",
  "lot-id",
  "batch-number",
  "material-type",
  "quantity",
  "location",
  // Personnel
  "presence",
  "task-id",
  "assigned-task",
  "role",
  // Process segment
  "start-time",
  "end-time",
  "duration",
  "output-quantity",
  // Quality
  "inspection-result",
  "deviation",
  "pass-fail",
  "surface-defect",
  "hardness",
  "tensile-strength",
  // Utilities / energy
  "pressure",
  "flow",
  "consumption",
  "alarm",
] as const;

// Contextual hints by object type. This is advisory only; unknown attributes are still allowed.
export const KnownAttributesByObjectType: Record<string, readonly string[]> = {
  equipment: [
    "status",
    "measured-temperature",
    "measured-vibration",
    "measured-pressure",
    "measured-flow",
    "operating-hours",
    "fault-code",
    "speed",
    "energy-consumption",
    "power",
    "voltage",
    "current",
  ],
  material: [
    "lot",
    "lot-id",
    "batch-number",
    "material-type",
    "quantity",
    "location",
    "status",
  ],
  personnel: [
    "presence",
    "task-id",
    "assigned-task",
    "role",
    "status",
  ],
  "process-segment": [
    "start-time",
    "end-time",
    "duration",
    "status",
    "output-quantity",
  ],
  "product-definition": [
    "product-code",
    "revision",
    "specification",
    "target-parameters",
    "material-composition",
    "version-history",
  ],
  "product-quality": [
    "inspection-result",
    "deviation",
    "pass-fail",
    "surface-defect",
    "hardness",
    "tensile-strength",
  ],
  "work-definition": [
    "work-order-id",
    "task-list",
    "planned-start",
    "planned-end",
    "assigned-to",
    "instruction-url",
  ],
  "resource-status": [
    "availability",
    "utilization",
    "downtime",
    "status",
    "maintenance-status",
  ],
  "energy-resource": [
    "power",
    "energy",
    "voltage",
    "current",
    "frequency",
    "cost",
  ],
  "utility-resource": [
    "pressure",
    "flow",
    "consumption",
    "status",
    "alarm",
  ],
  "fluid-resource": [
    "flow",
    "pressure",
    "temperature",
    "total-flow",
    "conductivity",
    "ph",
  ],
  "consumable-resource": [
    "level",
    "consumption-rate",
    "refill-required",
    "last-refill",
    "status",
  ],
};
