/* Auto-generated placeholder. Run generate-uns-measurements.ts to regenerate. */
export const GeneratedPhysicalMeasurements = {
  "None": "",
  "MiliMeter": "mm",
  "Meter": "m",
  "KiloMeter": "km",
  "Feet": "ft",
  "Second": "s",
  "Minute": "min",
  "Hour": "h",
  "Day": "day",
  "Hertz": "Hz",
  "CubicMeter": "m^3",
  "Liter": "l",
  "Gallon": "gal",
  "Psi": "psi",
  "Pascal": "Pa",
  "Bar": "bar",
  "Celsius": "°C",
  "Fahrenheit": "°F",
  "Kelvin": "K",
  "Milijoule": "mJ",
  "Joule": "J",
  "Kilojoule": "kJ",
  "Megajoule": "MJ",
  "Gigajoule": "GJ",
  "Terajoule": "TJ",
  "Newton": "N",
  "Bit": "bit",
  "Byte": "byte",
  "B": "B",
  "MilimeterPerSecond": "mm/s",
  "MeterPerSecond": "m/s",
  "MeterPerMinute": "m/min",
  "CentiMeterPerSecond": "cm/s",
  "MeterPerHour": "m/h",
  "KilometerPerHour": "km/h",
  "RevolutionsPerMinute": "rpm",
  "Percent": "percent",
  "PartsPerMillion": "ppm",
  "PartsPerBillion": "ppb",
  "PartsPerTrillion": "ppt",
  "Decibel": "dB",
  "Degree": "°",
  "Radian": "rad",
  "Miligram": "mg",
  "Gram": "g",
  "Kilogram": "kg",
  "MetricTon": "t",
  "MiliVolt": "mV",
  "Volt": "V",
  "KiloVolt": "kV",
  "MegaVolt": "MV",
  "MiliAmpere": "mA",
  "Ampere": "A",
  "KiloAmpere": "kA",
  "MegaAmpere": "MA",
  "MiliWatt": "mW",
  "Watt": "W",
  "KiloWatt": "kW",
  "MegaWatt": "MW",
  "MiliWattHour": "mWh",
  "WattHour": "Wh",
  "KiloWattHour": "kWh",
  "MegaWattHour": "MWh",
  "MiliVoltAmpere": "mVA",
  "VoltAmpere": "VA",
  "KiloVoltAmpere": "kVA",
  "MegaVoltAmpere": "MVA",
  "MiliVoltAmpereReactive": "mVAR",
  "VoltAmpereReactive": "VAR",
  "KiloVoltAmpereReactive": "kVAR",
  "MegaVoltAmpereReactive": "MVAR",
  "CubicMeterPerHour": "m^3/h",
  "CubicMeterPerSecond": "m^3/s",
  "MegaGramPerHour": "Mg/h",
  "MetricTonPerHour": "t/h",
} as const;

export const GeneratedDataSizeMeasurements = {
  "Bit": "bit",
  "Byte": "B",
  "KiloByte": "kB",
  "MegaByte": "MB",
  "GigaByte": "GB",
  "TeraByte": "TB",
  "PetaByte": "PB",
  "ExaByte": "EB",
  "ZettaByte": "ZB",
  "YottaByte": "YB",
} as const;

export const GeneratedCounterMeasurements = {
  "Kilo": "k",
  "Mega": "M",
  "Giga": "G",
} as const;

export type GeneratedPhysicalMeasurement = typeof GeneratedPhysicalMeasurements[keyof typeof GeneratedPhysicalMeasurements];
export type GeneratedDataSizeMeasurement = typeof GeneratedDataSizeMeasurements[keyof typeof GeneratedDataSizeMeasurements];
export type GeneratedCounterMeasurement = typeof GeneratedCounterMeasurements[keyof typeof GeneratedCounterMeasurements];
export type GeneratedMeasurementUnit = GeneratedPhysicalMeasurement | GeneratedDataSizeMeasurement | GeneratedCounterMeasurement | (string & {});
